name: deepfold2-dev
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.26
  - scipy=1.11
  - pandas=2.0
  - biopython=1.81
  - hydra-core=1.3.2
  - omegaconf=2.3.0
  - pytorch=2.1.0
  - pytorch-cuda=12.1
  - torchaudio
  - torchvision
  - isort
  - black
  - mkdocs
  - mkdocs-literate-nav
  - mkdocs-material
  - mkdocstrings-python

