name: deepfold2-dev
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.26.0
  - scipy=1.11.3
  - pandas=2.1.3
  - biopython=1.81
  - hydra-core-1.3.2
  - omegaconf=2.3.0
  - pytorch=2.1.1
  - pytorch-cuda=12.1
  - torchaudio
  - torchvision
  - isort
  - black
  - pip:
      - mkdocs
      - mkdocs-literate-nav
      - mkdocs-material
      - mkdocstrings
      - mkdocstrings-python
      - jax[cpu]=0.4.20
      - dm-haiku=0.0.11
      - dm-tree=0.1.8
