name: deepfold2-dev
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - scipy=
  - pandas
  - biopython=1.81
  - hydra-core
  - omegaconf
  - pytorch=2.1.1
  - pytorch-cuda=12.1
  - torchaudio
  - torchvision
  - isort
  - black
  - pip:
      - mkdocs
      - mkdocs-literate-nav
      - mkdocs-material
      - mkdocstrings
      - mkdocstrings-python
      - jax[cpu]
      - dm-haiku
      - dm-tree
