name: deepfold2-dev
channels:
  - pytorch
  - nvidia
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - scipy
  - pandas
  - matplotlib
  - biopython==1.81
  - hydra-core
  - omegaconf==2.3.0
  - pytorch=2.1.1
  - pytorch-cuda==12.1
  - torchaudio
  - torchvision
  - hmmer==3.3.2
  - hhsuite==3.3.0
  - kalign2==2.04
  - isort
  - black
  - pip:
      - mkdocs
      - mkdocs-literate-nav
      - mkdocs-material
      - mkdocstrings
      - mkdocstrings-python
      - jax[cpu]==0.4.20
      - dm-haiku==0.0.11
      - dm-tree==0.1.8
